# -*- encoding: utf-8 -*-

=begin
#ForestVPN Cloud API

#ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 

The version of the OpenAPI document: 2.0
Contact: support@forestvpn.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "forestvpn_cloud_api/version"

Gem::Specification.new do |s|
  s.name        = "forestvpn_cloud_api"
  s.version     = ForestVPNCloudAPI::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Digital Services LLC"]
  s.email       = ["support@forestvpn.com"]
  s.homepage    = "https://forestvpn.com/"
  s.summary     = "A package to interact api.forestvpn.com/cloud/ (manage vpn profiles / check usage statistics / manage locations / manage servers / etc)"
  s.description = "ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. "
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
