=begin
#ForestVPN Cloud API

#ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 

The version of the OpenAPI document: 2.0
Contact: support@forestvpn.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ForestVPNCloudAPI::GeoApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GeoApi' do
  before do
    # run before each test
    @api_instance = ForestVPNCloudAPI::GeoApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GeoApi' do
    it 'should create an instance of GeoApi' do
      expect(@api_instance).to be_instance_of(ForestVPNCloudAPI::GeoApi)
    end
  end

  # unit tests for list_locations
  # Location list
  # @param [Hash] opts the optional parameters
  # @return [Array<Location>]
  describe 'list_locations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
