=begin
#ForestVPN Cloud API

#ForestVPN Cloud - it's a Google Cloud but for VPN apps. Ready to use VPN Cloud Platform minimizes efforts to build fast, secure, and modern VPN apps. 

The version of the OpenAPI document: 2.0
Contact: support@forestvpn.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

# Common files
require 'forestvpn_cloud_api/api_client'
require 'forestvpn_cloud_api/api_error'
require 'forestvpn_cloud_api/version'
require 'forestvpn_cloud_api/configuration'

# Models
require 'forestvpn_cloud_api/models/action'
require 'forestvpn_cloud_api/models/activity'
require 'forestvpn_cloud_api/models/address'
require 'forestvpn_cloud_api/models/billing'
require 'forestvpn_cloud_api/models/country'
require 'forestvpn_cloud_api/models/create_billing_request'
require 'forestvpn_cloud_api/models/create_or_update_data_usage_limit_request'
require 'forestvpn_cloud_api/models/create_or_update_payment_profile_request'
require 'forestvpn_cloud_api/models/create_or_update_profile_request'
require 'forestvpn_cloud_api/models/data_usage_limit'
require 'forestvpn_cloud_api/models/error'
require 'forestvpn_cloud_api/models/location'
require 'forestvpn_cloud_api/models/payment_method'
require 'forestvpn_cloud_api/models/payment_profile'
require 'forestvpn_cloud_api/models/profile'
require 'forestvpn_cloud_api/models/profile_stats'
require 'forestvpn_cloud_api/models/project'
require 'forestvpn_cloud_api/models/resource_ref'
require 'forestvpn_cloud_api/models/user'

# APIs
require 'forestvpn_cloud_api/api/geo_api'
require 'forestvpn_cloud_api/api/limits_api'
require 'forestvpn_cloud_api/api/profiles_api'

module ForestVPNCloudAPI
  class << self
    # Customize default settings for the SDK using block.
    #   ForestVPNCloudAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
